IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'FirstName')) 
BEGIN
	 ALTER TABLE AspNetUsers ADD FirstName NVARCHAR(20) NULL
END
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'MiddleName')) 
BEGIN
	 ALTER TABLE AspNetUsers ADD MiddleName NVARCHAR(20) NULL
END
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'LastName')) 
BEGIN
	 ALTER TABLE AspNetUsers ADD LastName NVARCHAR(20) NULL
END
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'Suffix')) 
BEGIN
	 ALTER TABLE AspNetUsers ADD Suffix VARCHAR(5) NULL
END
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'ProfileDescription')) 
BEGIN
	 ALTER TABLE AspNetUsers ADD ProfileDescription nvarchar(500) NULL
END
	IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'Active')) 
BEGIN
	 ALTER TABLE AspNetUsers ADD Active BIT NULL
END
	IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'CreatedOn')) 
BEGIN
	 ALTER TABLE AspNetUsers ADD CreatedOn DATETIME NULL
END
	IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'CreatedBy')) 
BEGIN
	 ALTER TABLE AspNetUsers ADD CreatedBy BIGINT NULL
END
	IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'UpdatedOn')) 
BEGIN
	 ALTER TABLE AspNetUsers ADD UpdatedOn DATETIME NULL
END
	IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'UpdatedBy')) 
BEGIN
	 ALTER TABLE AspNetUsers ADD UpdatedBy BIGINT NULL
END
	