IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Files' AND COLUMN_NAME = 'QuestionId')) 
BEGIN
ALTER TABLE Files DROP CONSTRAINT DF_Files_QuestionId;
     ALTER TABLE Files DROP COLUMN QuestionId;
END
IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Files' AND COLUMN_NAME = 'Path')) 
BEGIN
     ALTER TABLE Files DROP COLUMN [Path];
     ALTER TABLE Files ADD [Type] [nvarchar](30) NULL;
END